// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuVgXEnxmCZQd3Ys_gtNc7_62ew0URnw',
    appId: '1:116957340443:web:1997fdd0271f053b6969be',
    messagingSenderId: '116957340443',
    projectId: 'chatpt-9513d',
    authDomain: 'chatpt-9513d.firebaseapp.com',
    storageBucket: 'chatpt-9513d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnADHI-0A79EHYMxNiZwcVdeHMGoIMQG0',
    appId: '1:116957340443:android:e007a03a9a3542276969be',
    messagingSenderId: '116957340443',
    projectId: 'chatpt-9513d',
    storageBucket: 'chatpt-9513d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPT4BFH_UPLmepbrPd7mQD1ZUlXzLkgcM',
    appId: '1:116957340443:ios:4c5b7dd50a00d2376969be',
    messagingSenderId: '116957340443',
    projectId: 'chatpt-9513d',
    storageBucket: 'chatpt-9513d.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPT4BFH_UPLmepbrPd7mQD1ZUlXzLkgcM',
    appId: '1:116957340443:ios:4c5b7dd50a00d2376969be',
    messagingSenderId: '116957340443',
    projectId: 'chatpt-9513d',
    storageBucket: 'chatpt-9513d.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfuVgXEnxmCZQd3Ys_gtNc7_62ew0URnw',
    appId: '1:116957340443:web:1997fdd0271f053b6969be',
    messagingSenderId: '116957340443',
    projectId: 'chatpt-9513d',
    authDomain: 'chatpt-9513d.firebaseapp.com',
    storageBucket: 'chatpt-9513d.firebasestorage.app',
  );

}